live_config_reload = true
working_directory = "None"

# Themes --
import = [
#  "~/.config/alacritty/nordic.toml",
#  "~/.config/alacritty/cyber_punk_neon.toml",
  "~/.config/alacritty/breeze.toml",
  "~/.config/alacritty/keybinds.toml"
]

[font]
normal = { family = "JetBrainsMono nerd font", style = "Regular" }
bold = { family = "JetBrainsMono nerd font", style = "Bold" }
italic = { family = "JetBrainsMono nerd font", style = "Italic" }
bold_italic = { family = "JetBrainsMono nerd font", style = "Bold Italic" }
size = 10.0

[scrolling]
history=20000

[window]
dimensions = { columns = 105, lines = 35 }
padding = { x = 3, y = 3 }
dynamic_padding = true
blur = true
opacity = 0.9

[env]
TERM = "xterm-256color"

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true
